version: "3"
services:
  # Production container
  web:
    restart: unless-stopped
    image: paranoidphantom/550-web:latest
    build:
      context: .
      args:
        - NITRO_PRESET=node_cluster
    networks:
      - nginx
  fs_server:
    restart: unless-stopped
    image: paranoidphantom/550-server:latest
    build: ../550-fs
    volumes:
      - fs_server_vol:/usr/src/fs_server/db
    networks:
      - nginx

  # Preview container
  preview_web:
    restart: unless-stopped
    image: paranoidphantom/550-web:preview
    build:
      context: .
      args:
        - NITRO_PRESET=node-server
        - ACCESS=testers
    env_file:
      - ./.env.preview
    networks:
      - nginx
  
  # Nginx container
  nginx:
    restart: always
    image: paranoidphantom/550-nginx:latest
    build:
      context: ./nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
      - fs_server
      - preview_web
    networks:
      - nginx

volumes:
  fs_server_vol:

networks:
  nginx: