version: "3"
services:
  # Production container
  web:
    restart: unless-stopped
    image: paranoidphantom/550-web:latest
    build:
      context: .
      args:
        - NITRO_PRESET=node_cluster
    ports:
      - "3000:3000"
  fs_server:
    restart: unless-stopped
    image: paranoidphantom/550-server:latest
    build: ../550-fs
    ports:
      - "3001:3001"
    volumes:
      - fs_server_vol:/usr/src/fs_server/db

  # Preview container
  preview_web:
    restart: unless-stopped
    image: paranoidphantom/550-web:preview
    build:
      context: .
      args:
        - NITRO_PRESET=node-server
        - ACCESS=testers
    ports:
      - "3002:3002"
    env_file:
      - ./.env.preview
  
  # Nginx container
  nginx:
    restart: always
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
      - fs_server
      - preview_web

volumes:
  fs_server_vol:
