version: '3'
services:
  # Production containers
  web:
    restart: unless-stopped
    image: paranoidphantom/550-web:latest
    build:
      context: .
      args:
        - NITRO_PRESET=node_cluster
    ports:
      - "3000:3000"
  fs_server:
    restart: unless-stopped
    image: paranoidphantom/550-server:latest
    build: ../550-fs
    ports:
      - "3001:3001"
    volumes:
      - fs_server_vol:/usr/src/fs_server/db

  # Preview containers
  preview_web:
    restart: unless-stopped
    image: paranoidphantom/550-web:preview
    build:
      context: .
      args:
        - NITRO_PRESET=node-server
        - ACCESS=testers
    ports:
      - "3002:3002"
    env_file:
      - ./.env.preview

  # Watchtower
  watchtower:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
    environment: 
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NOTIFICATIONS: slack
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "https://discord.com/api/webhooks/1215667608234360924/U8U94ILOFdYH8QTzkQsUhDpTaLTga9qDmaXkiBY6eBW-xEBMqofXcDDTBNKztz4WnVTj/slack"

volumes:
  fs_server_vol: