version: '3'
services:
  # Production containers
  web:
    restart: unless-stopped
    image: paranoidphantom/550-web:latest
    build: .
    network_mode: host
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  fs_server:
    restart: unless-stopped
    image: paranoidphantom/550-server:latest
    build: ../550-portal-server
    ports:
      - "3001:3001"
    volumes:
      - fs_server_vol:/usr/src/fs_server/db

  # Preview containers
  preview_web:
    restart: unless-stopped
    image: paranoidphantom/550-web:preview
    build: .
    network_mode: host
    ports:
      - "3002:3000"
    env_file:
      - ./.env
  preview_fs_server:
    restart: unless-stopped
    image: paranoidphantom/550-server:preview
    build: ../550-portal-server
    ports:
      - "3003:3001"
    volumes:
      - fs_server_vol:/usr/src/fs_server/db

  # Watchtower
  watchtower:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment: 
      WATCHTOWER_CLEANUP: "true"

volumes:
  fs_server_vol: