version: '3'
services:
  # Production containers
  web:
    restart: unless-stopped
    image: paranoidphantom/550-web:latest
    build:
      context: .
      args:
        - NITRO_PRESET=node_cluster
    ports:
      - "3000:3000"
    env_file:
      - ./.prod.env
  fs_server:
    restart: unless-stopped
    image: paranoidphantom/550-server:latest
    build: ../550-portal-server
    ports:
      - "3001:3001"
    volumes:
      - fs_server_vol:/usr/src/fs_server/db

  # Preview containers
  preview_web:
    restart: unless-stopped
    image: paranoidphantom/550-web:preview
    build:
      context: .
      args:
        - NITRO_PRESET=node-server
    ports:
      - "3002:3002"
    env_file:
      - ./.preview.env

  # Watchtower
  watchtower:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment: 
      WATCHTOWER_CLEANUP: "true"

volumes:
  fs_server_vol: