name: Docker deployment - Production

run-name: ❗ Docker | Deploy to production by @${{ github.actor }}

on:
    push:
        branches:
            - "master"

jobs:
    docker:
        runs-on: self-hosted
        environment: production
        concurrency: production
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: "Create env file"
              run: |
                  echo "${{ secrets.ENV_FILE }}\nNITRO_PRESET='node_cluster'" > .env
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: paranoidphantom/550-web:latest
                  build-args: |
                      NITRO_PRESET=node_cluster
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
