name: Docker deployment - Production

run-name: ❗ ${{github.event.head_commit.message}} - Production [${{ github.run_id }}]

on:
    push:
        branches:
            - "master"

jobs:
    Image-build:
        runs-on: ubuntu-latest
        environment: production
        concurrency: production
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: "Create .env file"
              run: |
                  echo -e "${{ secrets.ENV_FILE }}\nBUILD_ID=${{ github.run_id }}\nNITRO_PRESET='node_cluster'" > .env
            - name: Build and push - Main image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: paranoidphantom/550-web:latest
                  build-args: |
                      NITRO_PRESET=node_cluster
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
            - name: Build and push - Nginx
              uses: docker/build-push-action@v5
              with:
                  context: ./nginx
                  push: true
                  tags: paranoidphantom/550-nginx:latest
    Deploy:
        runs-on: self-hosted
        environment: preview
        needs: Image-build
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: "Creates supabase .env file"
              run: |
                  echo -e "${{ secrets.SUPABASE_ENV }}" > supabase/.env
            - name: Deploy preview
              run: |
                  docker compose up -d --pull 'always'
